# Datos con la historia sobre la visualización y los gráficos estadísticos.

dataBasic <- tibble::tribble(
  ~id, ~content, ~start, ~end,
  1, 'Primeros mapas y diagramas', '105', '1581',
  2, 'Medición del año con<br> precisión y construcción de la<br> primera carta estelar con<br> 850 estrellas.', '134', NA,
  3, 'Cálculo del diametro de la <br> tierra midiendo las sombras del<br> mediodía en sitios de 800 km.', '240', NA,
  4, 'Primer mapa de ruta pintado<br> sobre permgamino donde se<br> observa el mundo romano.', '335', NA,
  5, 'Intento de mostrar gráficamente<br> las posiciones del sol, la<br> luna y los planetas durante<br> todo el año.', '950', NA,
  6, 'Diagramas triangulares de<br> comparaciones pareadas en la elección<br> del Papa y la Madre Superiora.', '1280', NA,
  7, 'Diagramas mecánicos del<br> conocimiento como ayuda al<br> razonamiento.', '1305', NA,
  8, 'Desarrollo de la relación<br> entre tabular valores y<br> representarlos gráficamente.', '1350', NA,
  9, 'Atlas catalán, calendario<br> perpetuo y representación<br> temática del mundo conocido.', '1375', NA,
  10, 'Primer atlas moderno.', '1570', NA,
  11, 'Mejora en instrumentos<br> para medir la posición<br> de estrellas y planetas.', '1572', NA,
  12, 'Medición y teoria', '1600', '1699',
  13, 'Primeras tablas de datos<br> como una rama de la estadística<br> dedicada a la descripción numérica.', '1600', NA,
  14, 'Primeras imagenes astronómicas<br> en telescopio que ilustra el descubrimiento<br> de los cráteres en la luna, las 4<br> estaelitas de júpiter y estrellas.', '1610', NA,
  15, 'Primera máquina sumadora<br> conocida llamada reloj calculador<br> el cual sumaba y restaba<br> números de hasta 6 dígitos.', '1623', NA,
  16, 'Representación visual<br> usada para trazar los cambios<br> en las manchas solares.', '1626', NA,
  17, 'Análisis estadístico sobre<br> la ubicación de una estrella<br> basado en la idea de que la<br> hipótesis más probable es la<br> de desvió más pequeño.', '1632', NA,
  18, 'Introducción de sistemas<br> de coordenadas en matemáticas<br> y geometría analítica.', '1637', NA,
  19, 'Primera representación<br> visual de datos estadísticos <br> para determinar la longitud<br> entre Toledo y Roma.', '1644', NA,
  20, 'Declaración inicial de<br> la teoría de la probabilidad.', '1654', NA,
  21, 'Primer intento a<br> gran escala de una encuesta<br> científica y económica.', '1654', NA,
  22, 'Primer texto sobre probabilidad.', '1657', NA,
  23, 'Desarrollo de la idea<br> de que los registros de<br> bautizos y entierros podrían<br> usarse para hacer tablas<br> de vida.', '1662', NA,
  24, 'Primer censo demográfico completo<br> en habitantes de Nueva Francia.', '1666', NA,
  25, 'Primer gráfico de una<br> función de distribución continua y<br> gráfico de la tabla de vida de Gaunt.', '1669', NA,
  26, 'Primer mapa meteorológico<br> que muestra los vientos predominantes<br> en un mapa geográfico de la Tierra.', '1686', NA,
  27, 'Uso de estadísticas para<br> comparaciones internacionales sobre<br> personas, viviendas y hospitales.', '1687', NA,
  28, 'Primeras tablas de<br> mortalidad real que tiene las<br> edades al morir de individuos en<br> condiciones estables.', '1693', NA,
  29, 'Primer uso de áreas<br> de rectángulos para mostrar<br> probabilidades de eventos<br> binarios independientes.', '1693', NA,
  30, 'Nuevas formas gráficas', '1700', '1799'
  )
