# Datos con la historia sobre la visualización y los gráficos estadísticos.

dataBasic <- tibble::tribble(
  ~id, ~content, ~start, ~end,
  1, 'Primeros mapas y diagramas', '105', '1581',
  2, 'Medición del año con<br> precisión y construcción de la<br> primera carta estelar con<br> 850 estrellas.', '134', NA,
  3, 'Cálculo del diametro de la <br> tierra midiendo las sombras del<br> mediodía en sitios de 800 km.', '240', NA,
  4, 'Primer mapa de ruta pintado<br> sobre permgamino donde se<br> observa el mundo romano.', '335', NA,
  5, 'Intento de mostrar gráficamente<br> las posiciones del sol, la<br> luna y los planetas durante<br> todo el año.', '950', NA,
  6, 'Diagramas triangulares de<br> comparaciones pareadas en la elección<br> del Papa y la Madre Superiora.', '1280', NA,
  7, 'Diagramas mecánicos del<br> conocimiento como ayuda al<br> razonamiento.', '1305', NA,
  8, 'Desarrollo de la relación<br> entre tabular valores y<br> representarlos gráficamente.', '1350', NA,
  9, 'Atlas catalán, calendario<br> perpetuo y representación<br> temática del mundo conocido.', '1375', NA,
  10, 'Primer atlas moderno.', '1570', NA,
  11, 'Mejora en instrumentos<br> para medir la posición<br> de estrellas y planetas.', '1572', NA,
  12, 'Medición y teoria', '1600', '1699',
  13, 'Primeras tablas de datos<br> como una rama de la estadística<br> dedicada a la descripción numérica.', '1600', NA,
  14, 'Primeras imagenes astronómicas<br> en telescopio que ilustra el descubrimiento<br> de los cráteres en la luna, las 4<br> estaelitas de júpiter y estrellas.', '1610', NA,
  15, 'Primera máquina sumadora<br> conocida llamada reloj calculador<br> el cual sumaba y restaba<br> números de hasta 6 dígitos.', '1623', NA,
  16, 'Representación visual<br> usada para trazar los cambios<br> en las manchas solares.', '1626', NA,
  17, 'Análisis estadístico sobre<br> la ubicación de una estrella<br> basado en la idea de que la<br> hipótesis más probable es la<br> de desvió más pequeño.', '1632', NA,
  18, 'Introducción de sistemas<br> de coordenadas en matemáticas<br> y geometría analítica.', '1637', NA,
  19, 'Primera representación<br> visual de datos estadísticos <br> para determinar la longitud<br> entre Toledo y Roma.', '1644', NA,
  20, 'Declaración inicial de<br> la teoría de la probabilidad.', '1654', NA,
  21, 'Primer intento a<br> gran escala de una encuesta<br> científica y económica.', '1654', NA,
  22, 'Primer texto sobre probabilidad.', '1657', NA,
  23, 'Desarrollo de la idea<br> de que los registros de<br> bautizos y entierros podrían<br> usarse para hacer tablas<br> de vida.', '1662', NA,
  24, 'Primer censo demográfico completo<br> en habitantes de Nueva Francia.', '1666', NA,
  25, 'Primer gráfico de una<br> función de distribución continua y<br> gráfico de la tabla de vida de Gaunt.', '1669', NA,
  26, 'Primer mapa meteorológico<br> que muestra los vientos predominantes<br> en un mapa geográfico de la Tierra.', '1686', NA,
  27, 'Uso de estadísticas para<br> comparaciones internacionales sobre<br> personas, viviendas y hospitales.', '1687', NA,
  28, 'Primeras tablas de<br> mortalidad real que tiene las<br> edades al morir de individuos en<br> condiciones estables.', '1693', NA,
  29, 'Primer uso de áreas<br> de rectángulos para mostrar<br> probabilidades de eventos<br> binarios independientes.', '1693', NA,
  30, 'Nuevas formas gráficas', '1700', '1799',
  31, 'Primer mapa de contorno de<br> una variable basadado en datos.', '1701', NA,
  32, 'Primera prueba de significancia<br> estadística basada en el<br> desvió de los datos observados<br> y una hipótesis nula.', '1711', NA,
  33, 'Desarrollo del uso de<br> coordenadas polares para la<br> represetación de funciones.', '1736', NA,
  34, 'Inicios del estudio de la<br> estadística poblacional.', '1741', NA,
  35, 'Primer uso del término<br> estadística.', '1748', NA,
  36, 'Inicios de la estimación de<br> m cantidades desconocidas de n<br> ecuaciones empíricas (donde n > m).', '1750', NA,
  37, 'Diagramas Mayer desarrollados<br> para representar sistemas<br> de color.', '1758', NA,
  38, 'Observación de Lambert de que<br> un diagrama es mejor que una tabla.', '1765', NA,
  39, 'Aplicación de análisis gráfico<br> (gráfico líneal en mediciones).', '1767', NA,
  40, 'Desarrollo de la geometría descriptiva.', '1776', NA,
  41, 'Mapa geológico de Charpentier<br> (distribución de los minerales<br> en el suelo).', '1778', NA,
  42, 'Primera presentación semigráfica<br> que combina formatos tabulares<br> y gráficos.', '1779', NA,
  43, 'Primer mapa ecónomico y<br> temático (mapa estadístico de<br> producción en Europa).', '1782', NA,
  44, 'Uso de figuras geométricas<br> y proporcionales para comparar<br> cantidades demográficas por <br> superposición.', '1782', NA,
  45, 'Presentación de un gráfico<br> de barras de Playfair y gráficos<br> lineales de datos económicos.', '1786', NA,
  46, 'Registro automático de<br> datos bivariados (presión vs volumen).', '1796', NA,
  47, 'Invención de la técnica<br> litográfica para la impresión<br> de mapas y diagramas.', '1798', NA,
  48, 'Primer mapa de incidencia<br> de la enfermedad de fiebre<br> amarilla usando puntos y circulos<br> que muetran incidencias individuales.', '1798', NA,
  49, 'Principios de gráficos estadísticos de datos.', '1800', '1849',
  50, 'Primera idea para el<br> registro continuo de gráficos<br> de series de tiempo.', '1800', NA,
  51, 'Invención del gráfico circular<br> para mostrar relaciones de<br> parte a totalidad.', '1801', NA,
  52, 'Presentación del método<br> de mínimos cuadrados.', '1809', NA,
  53, 'Presentación de los gráficos<br> de Humbolt que usan gráficos<br> de barras ubdivididas y<br> cuadrados superpuestos.', '1811', NA,
  54, 'Primer gráfico de isotermas<br> que muestra la temperatura media<br> en todo el mundo según la<br> latitud y la longitud.', '1817', NA,
  55, 'Presentación del catograma de<br> Dupin, primer mapa coroplésico y<br> primer mapa estadístico moderno.', '1819', NA,
  56, 'Número creciente de públicaciones<br> científicas con gráficos y diagramas.', '1820', NA,
  57, 'Inicio de la informática como<br> es conocida hoy en día.', '1822', NA,
  58, 'Curva de Gompertz con el<br> fin de describir estadísticas<br> de mortalidad en organismos cuya<br> muerte aumenta con el tiempo.', '1825', NA,
  59, 'Comienza a aparecer el análisis<br> gráfico de fenómenos naturales<br> en publicaciones científicas.', '1830', NA,
  60, 'Ajuste de una curva suave<br> a un diagrama de dispersión y<br> declaración del método gráfico<br> como herramienta de la ciencia.', '1832', NA,
  61, 'Primera representación clasificada<br> de la densidad poblacional<br> en un mapa mundial.', '1833', NA,
  62, 'Primera apicación amplia<br> y general de los principios<br> de representación gráfica.', '1836', NA,
  63, 'Atlas físico de distribución<br> de plantas, animales y clima con<br> contenido de tablas y gráficos.', '1838', NA,
  64, 'Desarrollo de la curva<br> logística, y=k/(1+Ce^{rt}),<br> para describir el crecimiento<br> de poblaciones humanas.', '1839', NA,
  65, 'Mapas etnográficos de<br> Pritchard de la distribución<br> de grupos étnicos en el mundo.', '1843', NA,
  66, 'Aparición de la calculadora<br> universal de Lalanne que combina<br> cálculos logarítmicos y trigonométricos.', '1846', NA,
  67, 'Resultados mediante histogramas<br> simétricos del muestreo en urnas con <br> curvas de posibilidad limitante<br> (más tarde denominada curva normal).', '1846', NA
  )
