# Datos con la historia sobre la visualización y los gráficos estadísticos.

dataBasic <- tibble::tribble(
  ~id, ~content, ~start, ~end,
  1, 'Primeros mapas y diagramas', '105', '1581',
  2, 'Medición del año con<br> precisión y construcción de la<br> primera carta estelar con<br> 850 estrellas.', '134', NA,
  3, 'Cálculo del diametro de la <br> tierra midiendo las sombras del<br> mediodía en sitios de 800 km.', '240', NA,
  4, 'Primer mapa de ruta pintado<br> sobre permgamino donde se<br> observa el mundo romano.', '335', NA,
  5, 'Intento de mostrar gráficamente<br> las posiciones del sol, la<br> luna y los planetas durante<br> todo el año.', '950', NA,
  6, 'Diagramas triangulares de<br> comparaciones pareadas en la elección<br> del Papa y la Madre Superiora.', '1280', NA,
  7, 'Diagramas mecánicos del<br> conocimiento como ayuda al<br> razonamiento.', '1305', NA,
  8, 'Desarrollo de la relación<br> entre tabular valores y<br> representarlos gráficamente.', '1350', NA,
  9, 'Atlas catalán, calendario<br> perpetuo y representación<br> temática del mundo conocido.', '1375', NA,
  10, 'Primer atlas moderno.', '1570', NA,
  11, 'Mejora en instrumentos<br> para medir la posición<br> de estrellas y planetas.', '1572', NA,
  12, 'Medición y teoria', '1600', '1699',
  13, 'Primeras tablas de datos<br> como una rama de la estadística<br> dedicada a la descripción numérica.', '1600', NA,
  14, 'Primeras imagenes astronómicas<br> en telescopio que ilustra el descubrimiento<br> de los cráteres en la luna, las 4<br> estaelitas de júpiter y estrellas.', '1610', NA,
  15, 'Primera máquina sumadora<br> conocida llamada reloj calculador<br> el cual sumaba y restaba<br> números de hasta 6 dígitos.', '1623', NA,
  16, 'Representación visual<br> usada para trazar los cambios<br> en las manchas solares.', '1626', NA,
  17, 'Análisis estadístico sobre<br> la ubicación de una estrella<br> basado en la idea de que la<br> hipótesis más probable es la<br> de desvió más pequeño.', '1632', NA,
  18, 'Introducción de sistemas<br> de coordenadas en matemáticas<br> y geometría analítica.', '1637', NA,
  19, 'Primera representación<br> visual de datos estadísticos <br> para determinar la longitud<br> entre Toledo y Roma.', '1644', NA,
  20, 'Declaración inicial de<br> la teoría de la probabilidad.', '1654', NA,
  21, 'Primer intento a<br> gran escala de una encuesta<br> científica y económica.', '1654', NA,
  22, 'Primer texto sobre probabilidad.', '1657', NA,
  23, 'Desarrollo de la idea<br> de que los registros de<br> bautizos y entierros podrían<br> usarse para hacer tablas<br> de vida.', '1662', NA,
  24, 'Primer censo demográfico completo<br> en habitantes de Nueva Francia.', '1666', NA,
  25, 'Primer gráfico de una<br> función de distribución continua y<br> gráfico de la tabla de vida de Gaunt.', '1669', NA,
  26, 'Primer mapa meteorológico<br> que muestra los vientos predominantes<br> en un mapa geográfico de la Tierra.', '1686', NA,
  27, 'Uso de estadísticas para<br> comparaciones internacionales sobre<br> personas, viviendas y hospitales.', '1687', NA,
  28, 'Primeras tablas de<br> mortalidad real que tiene las<br> edades al morir de individuos en<br> condiciones estables.', '1693', NA,
  29, 'Primer uso de áreas<br> de rectángulos para mostrar<br> probabilidades de eventos<br> binarios independientes.', '1693', NA,
  30, 'Nuevas formas gráficas', '1700', '1799',
  31, 'Primer mapa de contorno de<br> una variable basadado en datos.', '1701', NA,
  32, 'Primera prueba de significancia<br> estadística basada en el<br> desvió de los datos observados<br> y una hipótesis nula.', '1711', NA,
  33, 'Desarrollo del uso de<br> coordenadas polares para la<br> represetación de funciones.', '1736', NA,
  34, 'Inicios del estudio de la<br> estadística poblacional.', '1741', NA,
  35, 'Primer uso del término<br> estadística.', '1748', NA,
  36, 'Inicios de la estimación de<br> m cantidades desconocidas de n<br> ecuaciones empíricas (donde n > m).', '1750', NA,
  37, 'Diagramas Mayer desarrollados<br> para representar sistemas<br> de color.', '1758', NA,
  38, 'Observación de Lambert de que<br> un diagrama es mejor que una tabla.', '1765', NA,
  39, 'Aplicación de análisis gráfico<br> (gráfico líneal en mediciones).', '1767', NA,
  40, 'Desarrollo de la geometría descriptiva.', '1776', NA,
  41, 'Mapa geológico de Charpentier<br> (distribución de los minerales<br> en el suelo).', '1778', NA,
  42, 'Primera presentación semigráfica<br> que combina formatos tabulares<br> y gráficos.', '1779', NA,
  43, 'Primer mapa ecónomico y<br> temático (mapa estadístico de<br> producción en Europa).', '1782', NA,
  44, 'Uso de figuras geométricas<br> y proporcionales para comparar<br> cantidades demográficas por <br> superposición.', '1782', NA,
  45, 'Presentación de un gráfico<br> de barras de Playfair y gráficos<br> lineales de datos económicos.', '1786', NA,
  46, 'Registro automático de<br> datos bivariados (presión vs volumen).', '1796', NA,
  47, 'Invención de la técnica<br> litográfica para la impresión<br> de mapas y diagramas.', '1798', NA,
  48, 'Primer mapa de incidencia<br> de la enfermedad de fiebre<br> amarilla usando puntos y circulos<br> que muetran incidencias individuales.', '1798', NA,
  49, 'Principios de gráficos estadísticos de datos.', '1800', '1849',
  50, 'Primera idea para el<br> registro continuo de gráficos<br> de series de tiempo.', '1800', NA,
  51, 'Invención del gráfico circular<br> para mostrar relaciones de<br> parte a totalidad.', '1801', NA,
  52, 'Presentación del método<br> de mínimos cuadrados.', '1809', NA,
  53, 'Presentación de los gráficos<br> de Humbolt que usan gráficos<br> de barras ubdivididas y<br> cuadrados superpuestos.', '1811', NA,
  54, 'Primer gráfico de isotermas<br> que muestra la temperatura media<br> en todo el mundo según la<br> latitud y la longitud.', '1817', NA,
  55, 'Presentación del catograma de<br> Dupin, primer mapa coroplésico y<br> primer mapa estadístico moderno.', '1819', NA,
  56, 'Número creciente de públicaciones<br> científicas con gráficos y diagramas.', '1820', NA,
  57, 'Inicio de la informática como<br> es conocida hoy en día.', '1822', NA,
  58, 'Curva de Gompertz con el<br> fin de describir estadísticas<br> de mortalidad en organismos cuya<br> muerte aumenta con el tiempo.', '1825', NA,
  59, 'Comienza a aparecer el análisis<br> gráfico de fenómenos naturales<br> en publicaciones científicas.', '1830', NA,
  60, 'Ajuste de una curva suave<br> a un diagrama de dispersión y<br> declaración del método gráfico<br> como herramienta de la ciencia.', '1832', NA,
  61, 'Primera representación clasificada<br> de la densidad poblacional<br> en un mapa mundial.', '1833', NA,
  62, 'Primera apicación amplia<br> y general de los principios<br> de representación gráfica.', '1836', NA,
  63, 'Atlas físico de distribución<br> de plantas, animales y clima con<br> contenido de tablas y gráficos.', '1838', NA,
  64, 'Desarrollo de la curva<br> logística, y=k/(1+Ce^{rt}),<br> para describir el crecimiento<br> de poblaciones humanas.', '1839', NA,
  65, 'Mapas etnográficos de<br> Pritchard de la distribución<br> de grupos étnicos en el mundo.', '1843', NA,
  66, 'Aparición de la calculadora<br> universal de Lalanne que combina<br> cálculos logarítmicos y trigonométricos.', '1846', NA,
  67, 'Histogramas simétricos del<br> muestreo en urnas con curvas<br> de posibilidad limitante<br> (llamada luego curva normal).', '1846', NA,
  68, 'Edad de oro de los gráficos de datos', '1850', '1899',
  69, 'Primera conferencia<br> internacional de estadística', '1853', NA,
  70, 'Descubrimiento de la fuente<br> de una erpidemia de cólera<br> gracias a el uso de un<br> mapa de puntos en datos<br> epidemiológicos.', '1855', NA,
  71, 'Discusión de la estandarización<br> y clasificación de métodos<br> gráficos en el tercer congreso<br> internacional de estadística.', '1857', NA,
  72, 'Presentación de un mapa<br> meteorológico que condujo luego<br> al descubrimiento del<br> movimiento anticiclónico del<br> viento alrededor de zonas de<br> baja presión.', '1861', NA,
  73, 'Uso de diagramas estadísticos<br> usado en un libro de texto escolar.', '1868', NA,
  74, 'Presentación del mapa de<br> flujo de Minard de la marcha<br> de Napoleón en Moscú (llamado<br> el mejor gráfico jamás producido).', '1869', NA,
  75, 'Consignación del Congreso de los<br> Estados Unidos para el tratamiento<br> gráfico de las estadísticas.', '1872', NA,
  76, 'Uso de gráficos estadísticos por<br> parte del gobierno de Estados<br> Unidos en informes censales.', '1872', NA,
  77, 'Clasificación de gráficos<br> estadísticos por forma y<br> consideración de usos<br> apropiados del color.', '1872', NA,
  78, 'Aplicación de métodos gráficos<br> para explicar relaciones<br>fundamentales en termodinámica.', '1873', NA,
  79, 'Primer uso estadístico de un<br> mapa de contorno mediante el<br> estudio de la densidad poblacional.', '1874', NA,
  80, 'Diagrama de dispersión y<br> diagrama de correlación semi-gráfico.', '1874', NA,
  81, 'Primera ilustración de Galton de<br> la idea de correlación usando<br> tamaños de semillas de plantas.', '1875', NA,
  82, 'primer uso de diagramas<br> polares y diagramas para la<br> representación de datos.', '1877', NA,
  83, 'Primeras ideas de correlación<br> y regresión citando la medida<br> de robustez.', '1877', NA,
  84, 'Primer intento de estudiar,<br> describir e ilustrar métodos<br> gráficos disponibles para<br> datos experimentales.', '1878', NA,
  85, 'Se intriduce el termino gráfico<br> refiriendose a diagramas que<br> muestran analogías entre<br> enlaces químicos en moléculas.', '1878', NA,
  86, 'Presentación del albúm de gráficos<br> estadísticos, una serie anual<br> que muestra todas las<br> formas gráficas conocidas.', '1879', NA,
  87, 'Descripción literaria de la<br> vida en un mundo bidimensional<br> para personas que viven<br> en un mundo 3D.', '1884', NA,
  88, 'Presentación del gráfico de<br> superficie de correlación<br> normal y regresión e idea<br> de la distribución normal<br> bivariada.', '1885', NA,
  89, 'Revisión exhaustiva de todos<br> los gráficos estadísticos disponibles<br> y primer intento de clasificación<br> de formas gráficas.', '1885', NA,
  90, 'Primeros mapas anamórficos,<br> usando deformación del<br> tamaño espacial para mostrar<br> una variable cuantitativa.', '1888', NA,
  91, 'Mapas que muestran la<br> pobreza y riqueza mediante<br> códigos de colores, lo cual<br> transformo los métodos exisentes<br> de encuesta y mapeo.', '1889', NA,
  92, 'Uso de rectángulos de área<br> en un mapa para mostrar dos<br> variables y su producto.', '1896', NA,
  93, 'Edad oscura de los gráficos de datos', '1900', '1949',
  94, 'Intento para formular estándares<br> para procedimientos gráficos.', '1901', NA,
  95, 'Los diagramas estadísticos<br> comenzan a aparecer en<br>libros de textos.', '1910', NA,
  96, 'Presentación de un libro en<br> ingles dedicado exclusivamente<br> a gráficos estadísticos.', '1910', NA,
  97, 'Primera exposición internacional<br> con varias gráficas estadísticas<br> de expositores internacionales.', '1911', NA,
  98, 'Descubrimiento del concepto de<br> número atómico, basado en<br> gran medida en análisis gráfico.', '1913', NA,
  99, 'Posiblemente el primer curso<br> sobre métodos gráficos estadísticos:<br> "El método gráfico."', '1913', NA,
  100, 'Publicación sobre normas<br> para presentación gráfica para<br> ingenieros mecánicos.', '1914', NA,
  101, 'Creación de un comite de<br> gráficos por la Asociación<br> Americana de Estadística.', '1915', NA,
  102, 'Inicios de desarrollo de<br> la teoría estadística moderna<br> (distribuciones, aleatorización, probabilidad,<br> teoría de muestras pequeñas, análisis<br> de varianza, etc) por Fisher.', '1915', NA,
  103, 'Gráfico de Gantt diseñado<br> para mostrar el progreso<br> programado y real de proyectos.', '1917', NA,
  104, 'Curso universitario anual<br> en métodos gráficos en Cubberly.', '1918', NA,
  105, 'Numerosos libros de textos gráficos<br> que describen los principios de<br> la presentación gráfica', '1920', NA,
  106, 'Prueba experimental de<br> formas gráficas estadísticas.', '1926', NA,
  107, 'Tabla de eventos históricos<br> dibujados en papel.', '1930', NA,
  108, 'Primera revisión moderna<br> de la historia temprana de<br> los gráficos estadísticos.', '1937', NA,
  109, 'Primera computadora digital<br> puesta en servicio.', '1944', NA,
  110, 'Renacimiento de la visualización de datos', '1950', '1974',
  111, 'Creación de Fortran, primer<br> lenguaje de alto nivel en informática.', '1957', NA,
  112, 'Principios de gráficos estadísticos<br> dinámicos modernos', '1962', NA,
  113, 'Inicios del desarrollo en<br> análisis de datos por Tukey', '1965', NA,
  114, 'Desarrollo inicial de los<br> sistemas de información geográfica<br> combinando datos referenciados<br> espacialmente, modelos<br> espaciales y visualización basada<br> en mapas.', '1960', NA,
  115, 'Teoría integral de<br> símbolos gráficos y modos<br> de representación gráfica.', '1967', NA,
  116, 'Innovaciones gráficas por parte<br> de Tukey para análisis exploratorio<br> de datos: diagramas de caja y bigotes,<br> diagrama de tallo y hoja, diagramas<br> de ajuste bidireccional y extendido, <br> listas gráficas, rootogramas colgantes<br> y suspendidos.', '1969', NA,
  117, 'Primer sistema interactivo<br> de manipulación directa<br> en estadística.', '1969', NA,
  118, 'Presentación del diagrama<br> estrella (polígono irregular)<br> para presentar datos multivariados.', '1971', NA,
  119, 'Propuesta para usar gráficos<br> estadísticos en la presentación<br> de informes de indicadores<br> sociales, particularmente en televisión.', '1971', NA,
  120, 'Desarrollo del biplot, un método<br> para visualizar tanto las<br> observaciones como las variables<br> en un conjunto de datos multivariados.', '1971', NA,
  121, 'Dibujos animados de caras de Cheroff<br> para representar datos multivariados', '1973', NA,
  122, 'Presentación de una matriz<br> bivariada codificada por colores para<br> representar dos variables medidas.', '1974', NA,
  123, 'Inicio de verdaderos gráficos<br> interactivos en estadística, mediante<br> el primer sistema de rotación<br> estadística de datos tridimensionales.', '1974', NA,
  124, 'Visualización de datos de alta dimensión', '1975', '2000',
  125, 'Realización de pruebas experimentales<br> de gráficos estadísticos versus tablas,<br> cuyos hallazgos favorecieron a<br> estos últimos.', '1975', NA,
  126, 'Presentación de una tabla de 2x2<br> probada experimentalemente contra<br> otras formas.', '1977', NA,
  127, 'Creación de la Revista de Estadísticas<br> computacionales y gráficos de la<br> Asociación Americana de Estadística.', '1977', NA,
  128, 'Creación del lenguaje S,<br> un lenguaje y entorno para<br> computación estadística y gráficos.', '1978', NA,
  129, 'Diagrama de correlación<br> geográfica de Monmonier, que<br> muestra la relación entre dos<br> variables referenciadas espacialmente.', '1979', NA,
  130, 'Presentación de la pantalla dibujante<br> para tres variables, que<br> llevo luego a la matriz del<br> diagrama de dispersión.', '1981', NA,
  131, 'Presentación de gráficos estadísticos<br> interactivos y sistematizados.', '1987', NA,
  132, 'Presentación de gráficos interactivos<br> para múltiples series de tiempo<br> con manipulación directa.', '1988', NA,
  133, 'Presentación de gráficos estadísticos<br> vinculados interactivamente<br> a pantallas de mapeo.', '1989', NA,
  134, 'Uso de dimensiones anidadas para la<br> visualización de datos multidimensionales.', '1989', NA,
  135, 'Presentación de Lisp-Stat, un<br> entorno estadístico orientado<br> a objetos para computación<br> estadística y gráficos dinámicos.', '1990', NA,
  136, 'Visualización de datos multivariados<br> en el contexto de la historia de la vida.', '1990', NA,
  137, 'Desarrollo de gráficos para el<br> análisis visual para modelos<br> log-lineales, iniciando así<br> los métodos generales para<br> visualizar datos categóricos.', '1991', NA,
  138, 'Desarrollo y distribución pública<br> de sistemas altamente interactivos<br> para el análisis y visualización<br> de datos, como por ejemplo XGobi.', '1991', NA,
  139, 'Principios de extensión general de<br> métodos gráficos a datos categóricos.', '1992', NA,
  140, 'Visualización de datos cartográficos<br> de Dykes: un kit de herramientas de visualización<br> de mapas con herramientas gráficas<br> para ver datos, que incluye una amplia<br> gama de opciones de mapeo para el análisis<br> exploratorio de datos espaciales.', '1996', NA,
  141, 'Presentación de la gramática de<br> graficos, un sistema integral<br> de reglas gramaticales para<br> datos y gráficos dentro de un<br> marco computacional orientado<br> a objetos por parte de Wilkinson.', '1999', NA
  )
